In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
a=np.arange(0,10)

In [2]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x = np.ones((3,3), dtype=bool)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [4]:
for num in a:  
    if num % 2 != 0: 
       print(num)

1
3
5
7
9


In [5]:
for num in a:  
    if num % 2 != 0: 
        a[num]=-2
a      

array([ 0, -2,  2, -2,  4, -2,  6, -2,  8, -2])

In [6]:
A = a.reshape((2,5))
A

array([[ 0, -2,  2, -2,  4],
       [-2,  6, -2,  8, -2]])

In [12]:
a=np.array([1,2,3,4,5,6,7,8,9])
B= np.array([])
list = []
for num in a:  
    if num % 2 != 0 or num % 4 == 0: 
        list.append(num)
B=np.array([list])

In [13]:
B

array([[1, 3, 4, 5, 7, 8, 9]])

In [14]:
C=np.array([1,2,3,4,5,6,np.nan,8,7,9])

In [15]:
C

array([ 1.,  2.,  3.,  4.,  5.,  6., nan,  8.,  7.,  9.])

In [17]:
np.isnan(C)

array([False, False, False, False, False, False,  True, False, False,
       False])

In [18]:
C[np.isnan(C)]= 0

In [19]:
C

array([1., 2., 3., 4., 5., 6., 0., 8., 7., 9.])

In [20]:
(unique, counts) = np.unique(a, return_counts=True)
frequencies = np.array((unique, counts))
print(frequencies)

[[1 2 3 4 5 6 7 8 9]
 [1 1 1 1 1 1 1 1 1]]


In [21]:
c=np.arange(99,299)
c

array([ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
       112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124,
       125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137,
       138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150,
       151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163,
       164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176,
       177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189,
       190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202,
       203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
       216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228,
       229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241,
       242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254,
       255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267,
       268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 27

In [22]:
for num in c:
    if num%5==0 or num%7==0:
        if not(num%5==0 and num%7==0):
            print(num, end = " ")

100 110 112 115 119 120 125 126 130 133 135 145 147 150 154 155 160 161 165 168 170 180 182 185 189 190 195 196 200 203 205 215 217 220 224 225 230 231 235 238 240 250 252 255 259 260 265 266 270 273 275 285 287 290 294 295 

In [23]:
C

array([1., 2., 3., 4., 5., 6., 0., 8., 7., 9.])

In [24]:
x=C[::-1]

In [25]:
x

array([9., 7., 8., 0., 6., 5., 4., 3., 2., 1.])

In [26]:
C.dtype

dtype('float64')

In [27]:
C = pd.Categorical(C)
C.dtype

CategoricalDtype(categories=[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0], ordered=False)